"""'add rate_limit_logs table'

Revision ID: 850ea851ef59
Revises: 3d3642175dac
Create Date: 2026-03-21 15:42:23.906140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850ea851ef59'
down_revision: Union[str, Sequence[str], None] = '3d3642175dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rate_limit_logs_user_id_created_at', 'rate_limit_logs', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rate_limit_logs_user_id_created_at', table_name='rate_limit_logs')
    op.drop_table('rate_limit_logs')
    # ### end Alembic commands ###
